# Site settings
title: hi gain dev
email:
description: > # this means to ignore newlines until "baseurl:"
  Блог про программирование и о его изучении
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dev.dmytrohoi.com" # the base hostname & protocol for your site

# User setting
owner: Dmytro Hoi
email: dev@dmytrohoi.com
facebook_username:
twitter_username:
github_username: higaindev
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright: Dmytro Hoi

# API settings
google_api_key:

# Build settings
markdown: kramdown
